src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
from django.urls import path
from . import views

app_name   = 'pages'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('about', views.AboutView.as_view(), name='about'),
    path('sermons', views.SermonView.as_view(), name='sermons'),
    path('giving', views.GivingView.as_view(), name='giving'),
    path('outreach', views.OutreachView.as_view(), name='outreach'),
    path('branches', views.BranchesView.as_view(), name='branches'),
    path('store', views.StoreView.as_view(), name='store'),
    path('store/order', views.OrderView.as_view(), name='order'),
]

src/pages/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from pages.formatChecker import validate_file_size
# Create your models here.


class Sermon(models.Model):
    title = models.CharField(max_length=120)
    image_mobile = models.ImageField(upload_to='sermons/mobile/image', default='sermons/default.jpg')
    image_desktop = models.ImageField(upload_to='sermons/desktop/image', default='sermons/default.jpg')
    description = models.TextField()
    audio = models.FileField(upload_to='sermons/', blank=True, null=True, validators=[validate_file_size])
    date = models.DateField()
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    def get_image_filename(self, filename):
        title = self.title
        slug = slugify(title)
        return "%s-%s" % (slug, filename)

    def save(self, *args, **kwargs):
        if self.image_mobile and self.image_desktop:
            self.image_mobile.name = self.get_image_filename(self.image_mobile.name)
            self.image_desktop.name = self.get_image_filename(self.image_desktop.name)
            self.image_url = self.image_mobile.url
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('sermons', kwargs={'id': self.id})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Sermons'
        unique_together = ('title', 'date')
class Announcement(models.Model):
    event_type = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title
class Gallery(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='gallery/')
    date = models.DateField()
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = 'Galleries'

src/pages/views.py
from django.shortcuts import render
from django.views import View
from pages.models import Sermon, Announcement, Gallery

# Create your views here.
class IndexView(View):
    template_name = "templates/pages/index.html"
    def get(self, request):
        lastest_sermon = Sermon.objects.filter().order_by('-date').first()
        sermon = Sermon.objects.filter().order_by('-date')[:1]
        context = {"sermon": lastest_sermon}
        return render(request, self.template_name, context)

class AboutView(View):
    template_name = "templates/pages/about.html"

    def get(self, request):
        return render(request, self.template_name)

class SermonView(View):

    template_name = "templates/pages/sermon_transcription.html"
    def get(self, request):
        return render(request, self.template_name)

class GivingView(View):
    template_name = "templates/pages/giving.html"

    def get(self, request):
        return render(request, self.template_name)

class OutreachView(View):
    template_name = "templates/pages/outreach.html"

    def get(self, request):
        return render(request, self.template_name)

        
class StoreView(View):
    template_name = "templates/pages/store.html"
    def get(self, request):
        return render(request, self.template_name)

class OrderView(View):
    template_name = "templates/pages/order.html"
    def get(self, request):
        return render(request, self.template_name)

class BranchesView(View):
    template_name = "templates/pages/branches.html"
    def get(self, request):
        return render(request, self.template_name)

src/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{%static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{%static 'images/favicon/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href=" {%static 'images/favicon/favicon-16x16.png'%}">
    <link rel="manifest" href="{%static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{%static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta property="og:image" content="{%static 'images/logo_svg.svg' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>Dashboard</title>
</head>
<body>
    {%block content%}

    {%endblock%}
</body>
</html>

src/templates/pages/about.html
{% extends '../../dist/templates/pages/base.html' %}
{% block page_title %}About Christ's Love Church {% endblock %}
{% load static %}

{% block content %}
<section class="about mb-4">
<div class="m-auto text-center text-white">
    <h1>About Us</h1>
    <h3 class="text-light">Learn more about Christ’s Love Church</h3>
</div>
</section>
<section class="mission-statement mb-5">
    <div class="container">
        <div class="row text-center my-5">
            <h1 class="mb-3">Mission & Ministry</h1>
            <div class="col-md-1">

            </div>
            <div class="col-md-5 my-5">
                <h2 class="heading">Our Mission</h2>
                <div class="px-5">
                    <span>Christ’s Abounding Love Church is a Global Evangelical ministry with its headquarters in Accra, Ghana. <br>
                        We are passionate about reaching others with the Gospel. We are a local church with a global mission of reaching the ends of the world for the Lord Jesus Christ.</span>    
                </div>
            </div>

            <div class="col-md-5 my-5">
                <h2 class="heading">Our Ministry</h2>
                <div class="px-5">
                    <span>The work to reach the lost with the Gospel has already begun through several Gospel crusades. <br>
                        The Life & Purpose Conference and Help From Above Conference are annually held to incite many to fulfill the purpose of God for their lives.</span>
                
                </div>
            </div>
            <div class="col-md-1">

            </div>
        </div>
        
    </div>
</section>
<section class="beliefs my-5">
    <div class="container mt-5">
        <h1 class="text-center">Our Beliefs</h1>
        <h3><span>“Love is of God, & God is Love”</span></h3>
        <div class="row mb-5">
            <div class="counter col-lg-1 col-sm-3 position-relative">
                <span class="position-absolute top-50 start-50 translate-middle"> 1</span>
            </div>
            <div class="col-lg-11 col-sm-9">
                <h4>Sharing God’s Love</h4>
                <span>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</span>
            </div>
        </div>
        <div class="row mb-5 flex-row-reverse">
            <div class="counter col-lg-1 col-sm-3 position-relative">
                <span class="position-absolute top-50 start-50 translate-middle"> 2</span>
            </div>
            <div class="col-lg-11 col-sm-9">
                <h4>Love your Neighbour</h4>
                <span>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</span>
            </div>
        </div>
        <div class="row mb-5">
            <div class="counter col-lg-1 col-sm-3 position-relative">
                <span class="position-absolute top-50 start-50 translate-middle"> 3</span>
            </div>
            <div class="col-lg-11 col-sm-9">
                <h4>We Love God</h4>
                <span>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</span>
            </div>
        </div>
    </div>
</section>

<section class="leadership mb-5">
    <div class="container">
        <h1 class="text-center">Leadership</h1>
        <h3><span>Know more about your leaders</span></h3>
        <div class="leader-profile row py-3">
            <div class="col-md-4">
                <img src="{%static 'images/profile-img.png'%}" class='img-fluid'alt="">
            </div>
            <div class="col-md-8">
                <div class="py-5 pt-5 mt-4">
                    <h2>Rev. Mubarak Kwota</h2>
                <h4>Head Pastor - Christ’s Love Church, Head Quaters</h4>
                <p>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</p>
                <a href="">Learn more</a>
                </div>
                
            </div>
        </div>
    </div>
</section>
{%endblock%}

src/templates/pages/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Christ’s Abounding Love Church is a Global Evangelical ministry with its headquarters in Accra, Ghana.  We are passionate about reaching others with the Gospel. We are a local church with a global mission of reaching the ends of the world for the Lord Jesus Christ.">
  <meta name="keywords" content="Evangelism, Church, Global Evangelical ministry, Christ’s Abounding Love Church, Christ's Love Church">
  <meta property="og:image" content="{%static 'images/logo_svg.svg' %}">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link rel="apple-touch-icon" sizes="180x180" href="{%static 'images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{%static 'images/favicon/favicon-32x32.png'%}">
  <link rel="icon" type="image/png" sizes="16x16" href=" {%static 'images/favicon/favicon-16x16.png'%}">
  <link rel="manifest" href="{%static 'images/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{%static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  <title>{% block page_title %}{% endblock %}</title>
</head>

<body>
  <!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="logo" href="{%url 'pages:home' %}">
        <img src="{%static 'images/logo.png' %}" alt="logo">
      </a>
      <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link " href="{%url 'pages:sermons' %}">SERMONS</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{%url 'pages:outreach' %}">OUTREACH</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{%url 'pages:branches' %}">BRANCHES</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{%url 'pages:store' %}">STORE</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{%url 'pages:about'%}">ABOUT</a>
          </li>
        </ul>
      </div>
      <!-- Search sermons -->
      <form action="" method="">
          <button type="button" id="search-bar"  class="btn btn-b-n search-bar mx-2" data-bs-toggle="collapse"
          data-bs-target="#navbarTogglerDemo01">
              <i class="bi bi-search"></i>
          <input type="text" class="border-0 search-input" placeholder="Search for Sermons here">
        </button>

      <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse search-icon"
        data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01">
        <i class="bi bi-search"></i>
      </button>

      <a type="button" class="btn btn-accent btn-giving" href="{%url 'pages:giving'%}">
        Giving
      </a>

    </div>
  </nav>
  <!-- End Header/Navbar -->

  {% block content %}

  {% endblock %}

  <footer class="footer">
    <div class="container">
      <div class="row pt-5">
        <div class="col-md-3">
          <img src="{%static 'images/logo_white.png' %}" alt="">
          <div class="pt-4">
            <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget varius enim. Etiam vehicula
              semper massa, sit amet consequat libero.
            </span>
          </div>
          <div class="social-media d-flex justify-content-evenly pt-4">
            <a href=""><i class='bx bxl-youtube'></i></a>
            <a href=""><i class='bx bxl-twitter'></i></a>
            <a href=""> <i class='bx bxl-facebook'></i></a>
            <a href=""> <i class='bx bxl-instagram'></i></a>
          </div>

        </div>

        <div class="col-md-9 py-4">
          <div class="row ">
            <div class="col-lg-6 col-md-6 col-sm-12">
              <div class="row pb-3">
                <div class="col-6">
                  <div >
                    <h4>About</h4>
                    <a href="">Mission & Ministry <br></a>
                    <a href="">Leadership & Beliefs </a>
                  </div>
                  </div>
                  <div class="col-6">
                    <div >
                      <h4>Ministries</h4>
                      <a href="">Sunday School<br></a>
                      <a href="">Outreach</a>
                    </div>
                  </div>
              </div>   
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
              <div class="row pb-3">
                <div class="col-6">
                  <div>
                    <h4>Branches</h4>
                    <a href="">Find a Location <br></a>
                    <a href="">Watch Party</a>
                  </div> 
                  </div>
                  <div class="col-6">
                    <div>
                      <h4>Media</h4>
                      <a href="">Sermons <br></a>
                      <a href="">Podcast</a>
                    </div>
                  </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 py-3">
              <h4>Contact Us</h4>
              <i class='bx bx-phone font-size-14 align-middle me-2'></i><span class="align-middle"><a href="tel:+233555358099">+233555358099</a></span><br>
              <i class='bx bx-envelope font-size-14 align-middle me-2'></i><span class="align-middle"> <a href="emailto:christsabounding@gmail.com">christsabounding@gmail.com</a></span>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 py-3"><h4>Useful links</h4>
              <i class='bx bx-chevron-right font-size-14 align-middle me-2'></i><span class="align-middle">Sunday School Donation</span><br>
              <i class='bx bx-chevron-right font-size-14 align-middle me-2'></i><span class="align-middle">Village Outreach</span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </footer>
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
</body>
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
</html>

src/templates/pages/branches.html
{% include './page_under_contruction.html' %}

src/templates/pages/giving.html
{% include './page_under_contruction.html' %}

src/templates/pages/index.html
{% extends '../../dist/templates/pages/base.html' %}
{% block page_title %}Christ's Love Church - Work for the Lord{% endblock %}
{% load static %}

{% block content %}

<section class="mt-5">
<div class="container sermon-section">
    <img src="{{ sermon.image_desktop.url }}" class="desktop-img" alt="Sermon Image Desktop">
    <img src="{{ sermon.image_mobile.url }}" class="mobile-img active" alt="Sermon Image Mobile">
    <div class="layer"></div>
    <div class="sermon-info pb-4 ms-2">
        <button class="btn btn-accent btn-latest rounded-pill">Latest Episode</button>
        <h3 class="sermon-title">Sharing the love of Christ</h3>
<div class="btn-group btn-group-justified " role="group" aria-label="Button group">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-primary m-1">Watch Now</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-outline m-1">More Episodes</button>
  </div>
</div>


    </div>
</div>
</section>

<section id="experience" class="mt-5">
    
    <div class="container experience-section mb-4">
        <h2>Let’s tailor your Experience</h2>
        <div class="row">
            <div class="col-lg-8">
                    <div class="card shadow rounded border-0">
                        <a type="button" class="card-body" href="">
                             <h4><i class="bi bi-geo-alt me-3"></i>Already part of a campus society?</h4>
                        </a>
                      </div>    
                    <div class="card rounded  shadow mt-3 border-0 ">
                        <a type="button" class="card-body " href="">
                            <h4><i class="bi bi-person me-3"></i>Visitor here?</h4>
                        </a>
                      </div>
                      <div class="card rounded shadow mt-3 mb-3 border-0" >
                        <a type="button" class="card-body " href="">
                            <h4><i class="bi bi-heart-pulse me-3"></i>Join a group</h4>
                        </a>
                      </div>
                  <div class="main-event">
                    <img src="{%static 'images/pastor.jpg' %}" class="desktop-img" alt="Sermon-img">
                    <img src="{%static 'images/pastor2.jpg' %}" class="mobile-img" alt="Sermon-img">
                    <div class="event-info ms-3 mb-4">
                        <button class="btn btn-accent btn-latest rounded-pill">Conference</button>
                        <h3 class="sermon-title">Help from Above</h3>
                        <a type="button" class="btn btn-primary" href="">Learn more</a>
                      </div>
                </div>

            </div>
            
            <div class="announcement-section col-lg-4">
                <div class="row">
                  <div class="upcoming-event shadow">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item border-0 heading">
                        <h4>Upcoming Activities</h4>
                        <p>Stay informed on all church activities and ocassions</p>
                        <hr>
                    </li>
                      <li class="list-group-item border-0">
                        <div class="row">
                            <div class="col-1"><i class='bx bx-chevron-right font-size-14'></i></div>
                        <div class="col-11">
                            <h5>Prayer Retreat</h5>
                            <span>Prayer retreat with Rev. Mubarak Kwota <br></span>
                            <i class='bx bx-calendar me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">Mon - Fri</span>
                            <i class='bx bx-time-five me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">6:30pm each night</span>
                        </div>
                        </div>
                    </li>
                      <li class="list-group-item border-0">
                        <div class="row">
                            <div class="col-1"><i class='bx bx-chevron-right font-size-14'></i></div>
                        <div class="col-11">
                            <h5>Young People’s Week</h5>
                            <span>Join us for exciting programs for YPW celebration<br></span>
                            <i class='bx bx-calendar me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">Thur - Sat</span>
                            <i class='bx bx-time-five me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">6:30pm each night</span>
                        </div>
                        </div>
                    </li>
                      <li class="list-group-item border-0">
                        <div class="row">
                            <div class="col-1"><i class='bx bx-chevron-right font-size-14'></i></div>
                        <div class="col-11">
                            <h5>Leader’s meeting</h5>
                            <span>All organizational heads are encouraged to be present<br></span>
                            <i class='bx bx-calendar me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">Mon</span>
                            <i class='bx bx-time-five me-1 font-size-14 align-middle'></i><span class="me-3 align-middle ">8:00am</span>
                        </div>
                        </div>
                    </li>
                      <li class="list-group-item border-0">
                        <div class="row">
                            <div class="col-1"><i class='bx bx-chevron-right font-size-14'></i></div>
                        <div class="col-11">
                            <h5 ><a class="show-more" href="">Show More</a> </h5>
                            <span>Learn more on other activities happening this week...<br></span>
                        </div>
                        </div>
                    </li>
                    </ul>
                  </div>
                  <div class="social-media text-center mt-3 shadow">
                      <h3 class="pt-2">Follow Christ’s Love Church</h3>
                    <div class=" d-flex justify-content-evenly py-3">
                      <a href=""><i class='bx bxl-youtube'></i></a>
                    <a href=""><i class='bx bxl-twitter'></i></a>
                    <a href=""> <i class='bx bxl-facebook'></i></a>
                    <a href=""> <img src="{%static 'images/Instagram.svg'%}" alt=""></a>
                    </div>
                  </div>
                  </div>
            </div>
        </div>
    </div>
</section>

<section class="giving-section">
  <div class="container giving-text text-center">
    <h1 class="pb-3">Giving</h1>
    <h2><img src="{%static 'images/Vectorquote.svg' %}" alt=""></h2>
    <h2 class="py-3">Each of you should give what you have decided in your heart to give,
      not reluctantly or under compulsion, for  God loves a cheerful giver</h2>
    <h2 class="text-white pb-2">2 Corinthians 9:7</h2>
    <h2 class="pb-3"><img src="{%static 'images/Vectorquote1.svg' %}" alt=""></h2>
    <a href="" class="btn btn-lg btn-primary">GIVE TODAY</a>
  </div>
</section>

<section class="gallery mb-3">
  <div class="gtco-testimonials">
    <div class="container heading text-center">
      <h1>Our Gallery</h1>
    <h3>Hello there, are you new here? Let’s show you around</h3>
    <hr>
    
    </div>
    <div class="owl-carousel owl-carousel1 owl-theme">
      <div>
        <div class="card text-center">
          <img src="{%static 'images/children1.jpg'%}" class="card-img w-100" alt="...">
          <div class="card-img-overlay">
            <button class="btn btn-accent btn-latest rounded-pill">Sunday School</button>
          </div>
        </div>
      </div>
      <div> 
        <div class="card text-center">
          <img src="{%static 'images/children2.jpg'%}" class="card-img w-100" alt="...">
          <div class=" card-img-overlay ">
            <button class="btn btn-accent btn-latest rounded-pill">Sunday School</button>
          </div>
        </div>
      </div>
      <div>
        <div class="card text-center">
          <img src="{%static 'images/SundaySchoolgallery.jpg'%}" class="card-img w-100" alt="...">
          <div class=" card-img-overlay ">
            <button class="btn btn-accent btn-latest rounded-pill">Sunday School</button>
          </div>
        </div>
      </div>
      <div>
        <div class="card text-center">
          <img src="{%static 'images/children3.jpg'%}" class="card-img w-100" alt="...">
          <div class=" card-img-overlay ">
            <button class="btn btn-accent btn-latest rounded-pill">Sunday School</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

src/templates/pages/page_under_contruction.html
{% extends '../../dist/templates/pages/base.html' %}
{% block page_title %}Sermons - Christ's Love Church {% endblock %}
{% load static %}

{% block content %}
<section class="contruction">
    <div class="container text-center my-5">
    <h1 class="py-5">THIS PAGE IS UNDER CONSTRUCTION</h1>
</div>
</section>
{%endblock%}